#include "unity/unity.h"

#include <vmm.h>

void setUp(void)
{
}

void tearDown(void)
{
}

void test_layout_exact_half_open_boundaries(void)
{
    TEST_ASSERT_EQUAL_HEX32(0x00000000, USER_SPACE_START);
    TEST_ASSERT_EQUAL_HEX32(0xC0000000, USER_SPACE_END_EXCLUSIVE);
    TEST_ASSERT_EQUAL_HEX32(0xC0000000, DIRECT_MAP_START);
    TEST_ASSERT_EQUAL_HEX32(0xC1000000, DIRECT_MAP_END_EXCLUSIVE);
    TEST_ASSERT_EQUAL_HEX32(0xC1000000, KERNEL_HEAP_START);
    TEST_ASSERT_EQUAL_HEX32(0xE0000000, KERNEL_HEAP_END_EXCLUSIVE);
    TEST_ASSERT_EQUAL_HEX32(0xE0000000, KERNEL_DYNAMIC_START);
    TEST_ASSERT_EQUAL_HEX32(0xF0000000, KERNEL_DYNAMIC_END_EXCLUSIVE);
    TEST_ASSERT_EQUAL_HEX32(0xF0000000, KERNEL_RESERVED_START);
    TEST_ASSERT_EQUAL_HEX32(0xFF000000, KERNEL_RESERVED_END_EXCLUSIVE);
    TEST_ASSERT_EQUAL_HEX32(0xFF000000, KERNEL_STACK_START);
    TEST_ASSERT_EQUAL_HEX32(0xFFC00000, KERNEL_STACK_END_EXCLUSIVE);
    TEST_ASSERT_EQUAL_HEX32(0xFFC00000, RECURSIVE_START);
    TEST_ASSERT_EQUAL_HEX32(0xFFFFFFFF, RECURSIVE_LAST);
}

void test_layout_is_adjacent_and_page_aligned(void)
{
    TEST_ASSERT_EQUAL_HEX32(USER_SPACE_END_EXCLUSIVE, DIRECT_MAP_START);
    TEST_ASSERT_EQUAL_HEX32(DIRECT_MAP_END_EXCLUSIVE, KERNEL_HEAP_START);
    TEST_ASSERT_EQUAL_HEX32(KERNEL_HEAP_END_EXCLUSIVE,
                            KERNEL_DYNAMIC_START);
    TEST_ASSERT_EQUAL_HEX32(KERNEL_DYNAMIC_END_EXCLUSIVE,
                            KERNEL_RESERVED_START);
    TEST_ASSERT_EQUAL_HEX32(KERNEL_RESERVED_END_EXCLUSIVE,
                            KERNEL_STACK_START);
    TEST_ASSERT_EQUAL_HEX32(KERNEL_STACK_END_EXCLUSIVE, RECURSIVE_START);
    TEST_ASSERT_EQUAL_UINT32(0, DIRECT_MAP_START % PAGE_SIZE);
    TEST_ASSERT_EQUAL_UINT32(0, KERNEL_HEAP_START % PAGE_SIZE);
    TEST_ASSERT_EQUAL_UINT32(0, KERNEL_DYNAMIC_START % PAGE_SIZE);
    TEST_ASSERT_EQUAL_UINT32(0, KERNEL_RESERVED_START % PAGE_SIZE);
    TEST_ASSERT_EQUAL_UINT32(0, KERNEL_STACK_START % PAGE_SIZE);
    TEST_ASSERT_EQUAL_UINT32(0, RECURSIVE_START % PAGE_SIZE);
}

void test_recursive_and_stack_geometry(void)
{
    TEST_ASSERT_EQUAL_UINT32(1023, RECURSIVE_PDE_INDEX);
    TEST_ASSERT_EQUAL_HEX32(0xFFFFF000, RECURSIVE_PD_VADDR);
    TEST_ASSERT_EQUAL_HEX32(0xFFC00000, VMM_PAGE_TABLE_VADDR(0));
    TEST_ASSERT_EQUAL_HEX32(0xFFFFE000, VMM_PAGE_TABLE_VADDR(1022));
    TEST_ASSERT_EQUAL_UINT32(1, KSTACK_GUARD_PAGES);
    TEST_ASSERT_EQUAL_UINT32(1, KSTACK_PAGES);
    TEST_ASSERT_EQUAL_UINT32(2, KSTACK_SLOT_PAGES);
    TEST_ASSERT_EQUAL_UINT32(8192, KSTACK_SLOT_SIZE);
    TEST_ASSERT_EQUAL_UINT32(1536, KSTACK_SLOT_COUNT);
}

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_layout_exact_half_open_boundaries);
    RUN_TEST(test_layout_is_adjacent_and_page_aligned);
    RUN_TEST(test_recursive_and_stack_geometry);
    return UNITY_END();
}
